# -*- coding: utf-8 -*-
"""NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JNGOUyKR3N88XZaIg6COzcC6biTcUpbG
"""

!pip install transformers datasets torch spacy nltk evaluate bert_score textstat accelerate sacrebleu -q
!python -m spacy download en_core_web_sm

import pandas as pd
import numpy as np
import torch
from datasets import Dataset, load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer
)


# 1. ANALOGI KUE (The Cake Analogy)
cake_analogies = [
    ("Unsupervised Learning", "Learning patterns without labels.", "The Sponge Cake: The main body of the cake; it uses the most ingredients (data) but has no specific flavor yet."),
    ("Supervised Learning", "Training on labeled data.", "The Icing: The specific flavor added on top. It requires precise handling but is smaller in volume than the sponge."),
    ("Reinforcement Learning", "Learning through trial and error.", "The Cherry on Top: The finishing touch that perfects the cake based on feedback, but can't be the whole meal."),
    ("Training Data", "Raw info used for training.", "The Ingredients: Flour, sugar, eggs. Bad ingredients (bad data) make a bad cake, no matter how good the chef is."),
    ("Algorithms", "Rules for solving problems.", "The Recipe: Step-by-step instructions. If the recipe is wrong, the cake fails even with good ingredients."),
    ("Compute", "Processing power for training.", "The Oven: You need heat and time to bake the batter. You cannot 'un-bake' it once it's done."),
    ("Evaluation", "Testing model performance.", "Tasting: Checking a slice to see if it's good. Averages might look good, but one slice could still be burnt."),
    ("Deployment", "Releasing the model.", "Selling the Cake: Packaging it and giving it to customers."),
    ("Model Weights", "Parameters learned during training.", "Seasoning: Adjusting the amount of sugar or salt until the taste is perfect."),
    ("Hyperparameters", "Settings before training starts.", "Oven Settings: Setting the temperature and timer before you put the cake in.")
]

# 2. ANALOGI MOBIL (Generative AI)
car_analogies = [
    ("Foundation Model", "Adaptable large-scale model.", "The Engine Block: A powerful V8 engine that can be put into a truck, car, or boat depending on how it's tuned."),
    ("Prompt", "Input instruction.", "The Steering Wheel: It directs where the massive engine power should go."),
    ("Token", "Basic unit of text.", "Fuel Drops: The engine processes fuel drop-by-drop to keep running."),
    ("Context Window", "Memory limit.", "Windshield View: How much of the road you can see at once. A small windshield means you miss the upcoming turn."),
    ("Fine-Tuning", "Specializing a model.", "Tuning the Car: Adding a spoiler and turbocharger to a factory car to win a specific race."),
    ("Inference", "Using the model.", "Driving: You aren't building the car anymore; you're just driving it to your destination."),
    ("Hallucination", "Confident false info.", "GPS Glitch: The map confidently tells you to turn left into a lake."),
    ("Temperature", "Randomness setting.", "Suspension: Low temp is a stiff, predictable ride. High temp is a loose, bouncy, creative ride."),
    ("Latency", "Delay in response.", "Turbo Lag: The delay between stepping on the gas and feeling the car accelerate."),
    ("Checkpoint", "Saved model state.", "Pit Stop: Saving your progress so if the car breaks down, you don't have to start the race from the beginning.")
]

# 3. ANALOGI SEKOLAH & ALAM (Core Concepts)
core_analogies = [
    ("Neural Network", "Connected computing nodes.", "Traffic Network: Cars (data) flow through roads. If one road is blocked, traffic finds a new route."),
    ("Neuron", "Basic processing unit.", "The Student: Listens to a whisper, decides if it's important, and passes it on."),
    ("Layer", "Level of processing.", "Grade Level: 1st grade learns letters, 5th grade learns sentences, 12th grade learns essays."),
    ("Activation Function", "Firing threshold.", "The Bouncer: Checks your ID. If the signal isn't strong enough, you don't get in."),
    ("Backpropagation", "Error correction.", "The Blame Game: The project failed, so the boss goes back down the chain to fix the mistake."),
    ("Overfitting", "Memorizing noise.", "Memorizing the Textbook: You know the exact words but fail the test because the questions changed slightly."),
    ("Underfitting", "Too simple.", "Skimming: You only read the chapter titles and can't answer any detailed questions."),
    ("Bias", "Prejudice in data.", "Tinted Glasses: If you wear red glasses, the whole world looks red, even if it isn't."),
    ("Zero-Shot Learning", "No prior examples.", "Improvising: Playing a song you've never heard before just by knowing music theory."),
    ("Few-Shot Learning", "Few examples.", "Test Drive: Driving a car around the block twice to get the feel of it."),
    ("Chain of Thought", "Step-by-step reasoning.", "Show Your Work: Writing down the math steps, not just the final answer."),
    ("RAG", "Using external data.", "Open Book Exam: You can look up facts in the textbook to make sure you're right."),
    ("GAN", "Competing networks.", "Forger vs Detective: One makes fake paintings, the other spots them. Both get better by competing."),
    ("Transformer", "Self-attention architecture.", "Traffic Control: Watching every car at once to prevent accidents."),
    ("Encoder", "Input processor.", "The Scanner: Turns a paper document into digital code."),
    ("Decoder", "Output generator.", "The Printer: Turns digital code back into a readable picture.")
]

# 4. GLOSSARY TAMBAHAN
glossary_analogies = [
    ("Accuracy", "Correctness of predictions.", "Target Practice: How many arrows actually hit the bullseye?"),
    ("Algorithm", "Step-by-step rules.", "Cooking Recipe: Follow these exact steps to get the result."),
    ("Annotation", "Labeling data.", "Sticky Notes: Putting tags on items so you know what they are."),
    ("Anomaly Detection", "Finding outliers.", "Security Guard: Spotting the one person running in a crowd of walkers."),
    ("API", "Software interface.", "The Waiter: Takes your order to the kitchen and brings the food back."),
    ("Artificial General Intelligence (AGI)", "Human-level AI.", "The Universal Genius: A machine that can learn to do anything a human can do."),
    ("Automation", "Automatic tasks.", "Autopilot: The plane flies itself while the pilot drinks coffee."),
    ("Bag of Words", "Text representation.", "Word Soup: Throwing all words into a bowl without caring about grammar."),
    ("Batch", "Group of data.", "Laundry Load: Washing a pile of clothes together instead of one sock at a time."),
    ("Bayesian Network", "Probabilistic model.", "Weather Forecast: Predicting rain based on clouds, humidity, and wind."),
    ("Big Data", "Huge datasets.", "The Ocean: You can't drink it; you need a ship to navigate it."),
    ("Binary Classification", "Two-choice outcome.", "Coin Toss: It's either Heads or Tails, nothing else."),
    ("Black Box", "Opaque internal workings.", "Magician's Hat: You see the rabbit go in and come out, but don't know how."),
    ("Chatbot", "Conversational AI.", "Digital Receptionist: Answers common questions at the front desk."),
    ("Classification", "Categorizing data.", "Sorting Mail: Putting letters into the right zip code bins."),
    ("Cloud Computing", "Remote servers.", "Renting Tools: Using a giant crane from a rental company instead of buying one."),
    ("Clustering", "Grouping similar items.", "Sorting Laundry: Whites in one pile, colors in another."),
    ("Computer Vision", "AI seeing images.", "Digital Eyes: Teaching a camera to recognize a face."),
    ("Confusion Matrix", "Performance table.", "Scoreboard: Shows hits, misses, and false alarms."),
    ("Corpus", "Large text collection.", "The Library: The entire collection of books the AI reads."),
    ("Correlation", "Relationship between variables.", "Smoke and Fire: Where there's smoke, there's usually fire."),
    ("Cross-Validation", "Testing model stability.", "Rotation: Testing a player in different positions to see if they are actually good."),
    ("Data Augmentation", "Increasing data variety.", "Photocopying: Flipping and rotating a photo to create 'new' data."),
    ("Data Mining", "Finding patterns.", "Gold Panning: Sifting dirt to find nuggets of value."),
    ("Data Science", "Extracting knowledge.", "Detective Work: finding clues in the evidence."),
    ("Decision Tree", "Tree-like model.", "20 Questions Game: Is it an animal? Yes. Does it bark? No."),
    ("Deepfakes", "Synthetic media.", "Digital Mask: Putting a realistic mask on an actor."),
    ("Dimensionality Reduction", "Simplifying data.", "Shadow Puppets: A 3D hand makes a simple 2D shadow."),
    ("Discriminator", "Evaluating network in GAN.", "Art Critic: Deciding if the painting is real or fake."),
    ("Edge Computing", "Local processing.", "Reflexes: Pulling your hand from fire before your brain even thinks about it."),
    ("Embedding", "Vector representation.", "Barcode: A number that represents a complex product."),
    ("Ensemble Learning", "Combining models.", "Teamwork: A doctor, nurse, and surgeon working together is better than one alone."),
    ("Epoch", "Training cycle.", "Gym Reps: Doing a full set of exercises to build muscle."),
    ("Feature Extraction", "Isolating important parts.", "Juicing: Getting the liquid out and leaving the peel behind."),
    ("Feature", "Measurable property.", "Identity: Height, weight, and eye color are your features."),
    ("Feedforward Network", "Simple neural network.", "One-Way Street: Traffic only moves forward, never back."),
    ("F1 Score", "Balanced metric.", "Report Card: The average grade of your Math and English scores."),
    ("Garbage In, Garbage Out", "Quality principle.", "Rotten Cooking: If you use rotten eggs, the cake will be bad."),
    ("Generalization", "Performance on new data.", "Street Smarts: Using what you learned in school in the real world."),
    ("Generative AI", "Creating new content.", "The Artist: Painting a new picture, not just taking a photo."),
    ("Genetic Algorithm", "Evolutionary search.", "Survival of the Fittest: Only the best solutions 'survive' to the next round."),
    ("GPU", "Graphics Processor.", "Construction Crew: A thousand workers building a wall together (fast)."),
    ("Gradient", "Slope of error.", "Hill Slope: The steepness of the hill you are climbing down."),
    ("Ground Truth", "Actual reality.", "Answer Key: The correct answers to the test."),
    ("Heuristic", "Rule of thumb.", "Shortcut: Taking the back roads to avoid traffic."),
    ("Hidden Layer", "Internal processing.", "The Kitchen: Customers eat the food, but the cooking happens here, unseen."),
    ("Image Recognition", "Identifying images.", "FaceID: Your phone recognizing it's you."),
    ("Input Layer", "Data entry.", "Front Door: Where guests enter the building."),
    ("IoT", "Connected devices.", "Nervous System: Connecting all appliances to a central brain."),
    ("Iteration", "One update step.", "Baby Step: Taking one small step towards the destination."),
    ("K-Means", "Clustering algorithm.", "Seating Chart: Arranging wedding guests so similar people sit together."),
    ("KNN", "Nearest neighbors.", "Peer Pressure: You act like the 5 people closest to you."),
    ("Knowledge Graph", "Data connections.", "Mind Map: Drawing lines between related ideas."),
    ("Label", "Tagging data.", "Price Tag: Tells you what the item is worth."),
    ("Large Language Model", "Massive text AI.", "Encyclopedia: Knows a little bit about everything."),
    ("Learning Rate", "Adjustment speed.", "Steering Sensitivity: Turn the wheel too much and you crash; too little and you don't turn."),
    ("Linear Regression", "Predicting values.", "Trend Line: Drawing a line through dots on a graph."),
    ("Logistic Regression", "Predicting categories.", "Pass/Fail: Predicting if you will pass the exam based on study hours."),
    ("Loss", "Error value.", "Golf Score: The lower the score, the better you did."),
    ("Machine Learning", "Learning from data.", "Apprentice: Watching the master and learning to do it yourself."),
    ("Machine Translation", "Language to language.", "Babel Fish: Instantly understanding a foreign language."),
    ("Metadata", "Data about data.", "Library Card: Tells you where the book is, not the story itself."),
    ("Model", "The trained AI.", "The Brain: The final product that can think/predict."),
    ("Multimodal", "Multiple inputs.", "Swiss Army Knife: Can cut, saw, and screw via one tool."),
    ("Naive Bayes", "Probabilistic classifier.", "Stereotyping: Assuming it's a duck because it quacks."),
    ("Natural Language Generation", "Writing text.", "Ghostwriter: Writing a speech for you."),
    ("NLP", "Understanding text.", "Universal Translator: Understanding human speech."),
    ("Node", "Connection point.", "Intersection: Where two roads meet."),
    ("Noise", "Irrelevant data.", "Static: The fuzz on the radio that makes music hard to hear."),
    ("Normalization", "Scaling data.", "Currency Converter: Turning Dollars and Yen into Gold so they can be compared."),
    ("Object Detection", "Finding items.", "Where's Waldo: Finding the specific person in a crowd."),
    ("One-Hot Encoding", "Categorical to number.", "Switchboard: Turning on one specific light for each category."),
    ("Optimization", "Improving performance.", "Tuning: Adjusting a guitar string until it hits the perfect note."),
    ("Outlier", "Anomalous data.", "Black Sheep: The one item that doesn't fit the group."),
    ("Output Layer", "Final result.", "Checkout Counter: Where you get your receipt."),
    ("Parameter", "Internal variable.", "Knob: A control dial on a machine."),
    ("Pattern Recognition", "Finding structure.", "Cloud Gazing: Seeing shapes in the clouds."),
    ("Perceptron", "Single neuron.", "Light Switch: It's either on or off."),
    ("Pooling", "Downsampling.", "Squinting: Blurring your eyes to see the big picture, not details."),
    ("Precision", "Exactness.", "Needle in Haystack: Finding only the needle, not the hay."),
    ("Predictive Analytics", "Forecasting.", "Weather Report: Guessing rain based on clouds."),
    ("Preprocessing", "Cleaning data.", "Washing Veggies: Cleaning dirt before cooking."),
    ("Pre-trained Model", "Base model.", "College Graduate: Knows basics, needs job training."),
    ("Random Forest", "Ensemble trees.", "The Jury: Ideally, 12 people decide better than 1."),
    ("Recall", "Completeness.", "Fishing Net: Catching ALL the fish, even if you catch some boots."),
    ("Recommendation System", "Suggesting items.", "Personal Shopper: Suggesting clothes you might like."),
    ("Recurrent Neural Network", "Sequential memory.", "Diary: Remembering what happened yesterday to understand today."),
    ("Regression", "Predicting numbers.", "Crystal Ball: Predicting the exact stock price."),
    ("Regularization", "Preventing overfitting.", "Speed Bump: Slowing down the car so it doesn't crash."),
    ("Relu", "Activation function.", "Gatekeeper: Only lets positive energy through."),
    ("Robotics", "Physical AI.", "The Body: The hardware that moves, controlled by the AI brain."),
    ("Robustness", "Stability.", "Off-Road Tires: Works well even on bumpy roads."),
    ("Root Mean Square Error", "Error metric.", "Scorecard: How far off were your guesses?"),
    ("Scalability", "Growth potential.", "Elastic Band: Stretches to fit big or small items."),
    ("Segmentation", "Partitioning image.", "Color by Number: Coloring each section a specific color."),
    ("Self-Attention", "Context focus.", "Highlighting: Marking important words in a textbook."),
    ("Self-Supervised Learning", "Learning from itself.", "Fill in the Blank: Learning by guessing the missing word."),
    ("Semantic Analysis", "Meaning extraction.", "Reading Between the Lines: Understanding the mood, not just words."),
    ("Sentiment Analysis", "Emotion detection.", "Mood Ring: Detecting if the text is happy or sad."),
    ("Sequence to Sequence", "Input to output.", "Translation: English sentence in, French sentence out."),
    ("Sigmoid", "S-curve function.", "Dimmer Switch: Smoothly transitioning from off to on."),
    ("Softmax", "Probability distribution.", "Pie Chart: Showing percentages that add up to 100%."),
    ("Speech Recognition", "Audio to text.", "Stenographer: Typing what is spoken."),
    ("Structured Data", "Organized info.", "Excel Sheet: Rows and columns."),
    ("Supercomputer", "High performance.", "Hive Mind: Many brains working as one."),
    ("Support Vector Machine", "Classifier.", "The Fence: Drawing a line to separate sheep from goats."),
    ("Synthetic Data", "Fake data.", "Simulation: Video game world used for training."),
    ("Testing", "Verifying model.", "Final Exam: Checking if the student learned."),
    ("Text-to-Speech", "Reading aloud.", "Audiobook: Turning text into voice."),
    ("Time Series", "Temporal data.", "Stock Chart: Prices changing over time."),
    ("Tokenization", "Splitting text.", "Chopping: Cutting veggies into bite-sized pieces."),
    ("TPU", "Tensor Processor.", "Specialist: A worker who only does one job, but extremely fast."),
    ("Training", "Learning phase.", "Practice: Rehearsing before the big show."),
    ("Transfer Learning", "Reusing knowledge.", "Renaissance Man: Using math skills to learn coding."),
    ("Transformer", "Modern architecture.", "High-Speed Rail: Moves data faster than old trains."),
    ("Turing Test", "Human-like check.", "Blind Test: Can you tell if it's Coke or Pepsi?"),
    ("Underfitting", "Too simple.", "Blank Slate: Knowing nothing."),
    ("Unstructured Data", "Messy info.", "Junk Drawer: Random items mixed together."),
    ("Validation", "Tuning check.", "Pop Quiz: Checking progress before the final."),
    ("Variance", "Sensitivity.", "Jitter: Shaking hands when trying to aim."),
    ("Vector", "Direction and magnitude.", "Arrow: Pointing in a specific direction with force."),
    ("Virtual Assistant", "AI helper.", "Butler: Serves your requests."),
    ("Virtual Reality", "Simulated world.", "Dreaming: Being in a world that isn't there."),
    ("Visual Question Answering", "Seeing and speaking.", "Tour Guide: Looking at a statue and explaining it."),
    ("Weak AI", "Narrow task.", "Calculator: Good at math, bad at poetry."),
    ("Weight", "Connection strength.", "Muscle: Stronger weights mean stronger pull."),
    ("Word Embedding", "Word vector.", "Map Coordinates: Every word has a location on the map."),
    ("XAI", "Explainable AI.", "Glass Box: Seeing how the gears turn inside."),
    ("Zero-Shot", "No examples.", "Intuition: Guessing right without studying.")
]


full_data = []
full_data.extend(cake_analogies * 2)
full_data.extend(car_analogies * 2)
full_data.extend(core_analogies * 2)
full_data.extend(glossary_analogies)

full_data = full_data[:220]

df = pd.DataFrame(full_data, columns=["category", "technical_explanation", "simplified_analogy"])
df["source"] = "Curated (Cake/Car/Glossary)"

df.to_csv("new_200_ai_analogies.csv", index=False)
print(f"✅ Dataset READY: {len(df)} Real Data (No Dummy)")

MODEL_NAME = "google/flan-t5-small"
OUTPUT_DIR = "flan-t5-aisap-final"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

dataset = load_dataset("csv", data_files={"train": "new_200_ai_analogies.csv"})
dataset = dataset["train"].train_test_split(test_size=0.1, seed=42)

def preprocess_function(examples):
    inputs = [f"Explain {c} in a simple analogy:" for c in examples["category"]]
    model_inputs = tokenizer(inputs, max_length=128, truncation=True, padding="max_length")
    with tokenizer.as_target_tokenizer():
      labels = tokenizer(examples["simplified_analogy"], max_length=128, truncation=True, padding="max_length")

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

tokenized_datasets = dataset.map(preprocess_function, batched=True)
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

training_args = Seq2SeqTrainingArguments(
    output_dir=OUTPUT_DIR,
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-4,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    weight_decay=0.01,
    save_total_limit=1,
    num_train_epochs=20,
    predict_with_generate=True,
    fp16=False,
    logging_steps=10,
)

trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
)

print("Starting Training...")
trainer.train()
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("✅ Model Training Complete & Saved!")

def chat_inference():
    inf_tokenizer = AutoTokenizer.from_pretrained(OUTPUT_DIR)
    inf_model = AutoModelForSeq2SeqLM.from_pretrained(OUTPUT_DIR)

    print("\n" + "="*40)
    print("🤖 AISAP BOT IS READY! (Real Data)")
    print("Type 'Fine-Tuning', 'Algorithm', 'API', etc.")
    print("="*40)

    while True:
        user_input = input("\nYou: ")
        if user_input.lower() in ["quit", "exit"]:
            break

        prompt = f"Explain {user_input} in a simple analogy:"
        inputs = inf_tokenizer(prompt, return_tensors="pt", max_length=128, truncation=True).to(inf_model.device)

        output_ids = inf_model.generate(
            **inputs,
            max_new_tokens=100,
            num_beams=5,
            temperature=0.1,
            early_stopping=True
        )

        response = inf_tokenizer.decode(output_ids[0], skip_special_tokens=True)
        print(f"Bot: {response}")

if __name__ == "__main__":
    chat_inference()

